-- 3.a. Listar los pedidos con su cliente, tienda y total del pedido, además incluya un campo con la fecha actual.
SELECT o.order_id,
    c.full_name AS cliente,
    s.store_name AS tienda,
    SUM(oi.unit_price * oi.quantity) AS total_pedido,
    SYSDATE AS fecha_actual
FROM orders o
    JOIN customers c ON o.customer_id = c.customer_id
    JOIN stores s ON o.store_id = s.store_id
    JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY o.order_id,
    c.full_name,
    s.store_name;
-- 3.b. Listar los primeros 12 pedidos cuyo total sea mayor que el promedio de los totales de todos los pedidos. Incluya un campo con la fecha actual.
WITH Totales_Pedidos AS (
    SELECT order_id,
        SUM(unit_price * quantity) AS total
    FROM order_items
    GROUP BY order_id
),
Promedio_Total AS (
    SELECT AVG(total) AS prom
    FROM Totales_Pedidos
)
SELECT t.order_id,
    t.total,
    SYSDATE AS fecha_actual
FROM Totales_Pedidos t,
    Promedio_Total p
WHERE t.total > p.prom
FETCH FIRST 12 ROWS ONLY;
-- 3c. Listar las tiendas y el número de pedidos en cada una ( Utilizar LEFT JOIN), incluya un campo con la fecha actual.
SELECT s.store_name AS tienda,
    COUNT(o.order_id) AS numero_pedidos,
    SYSDATE AS fecha_actual
FROM stores s
    LEFT JOIN orders o ON s.store_id = o.store_id
GROUP BY s.store_name;
-- 3.d. Se tiene la siguiente consulta. Usted debe rediseñar la consulta optimizándola para obtener el mismo resultado, justifique la optimización usando la herramienta explain.
EXPLAIN PLAN FOR
SELECT c.full_name AS customer_name,
    s.store_name,
    SUM(oi.quantity * oi.unit_price) AS order_total,
    s.store_name AS city
FROM orders o
    JOIN customers c ON o.customer_id = c.customer_id
    JOIN stores s ON o.store_id = s.store_id
    JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY c.full_name,
    s.store_name;
/*
 La consulta original tiene subconsultas en el SELECT, lo cual es muy ineficiente porque se ejecutan por cada fila devuelta.
 Para visualizar el plan de ejecución y justificarlo en el trabajo:
 */
/*
 4.Implemente el particionamiento de la tabla ORDERS basada en la fecha de orden 
 Se trata de dividir la tabla en particiones anuales para mejorar la eficiencia de las consultas que buscan órdenes en un rango de fechas.
 Crear particiones de la tabla por rango de fechas usando el campo order_tms
 Ejecutar consultas para verificar el funcionamiento del particionamiento
 */
ALTER TABLE orders
MODIFY PARTITION BY RANGE (order_tms) (
        PARTITION p_2021
        VALUES LESS THAN (TIMESTAMP '2022-01-01 00:00:00'),
            PARTITION p_2022
        VALUES LESS THAN (TIMESTAMP '2023-01-01 00:00:00'),
            PARTITION p_2023
        VALUES LESS THAN (TIMESTAMP '2024-01-01 00:00:00'),
            PARTITION p_2024
        VALUES LESS THAN (TIMESTAMP '2025-01-01 00:00:00'),
            PARTITION p_2025
        VALUES LESS THAN (TIMESTAMP '2026-01-01 00:00:00'),
            PARTITION p_max
        VALUES LESS THAN (MAXVALUE)
    ) ONLINE;
/*
 5. Diseñar un procedimiento almacenado que actualice los precios de todos los productos en una tienda específica 
 El procedimiento debe recibir el ID de la tienda y el porcentaje de aumento. Ejecutar el procedimiento y verificar los resultados en la tabla PRODUCTS e INVENTORY.
 */
CREATE OR REPLACE PROCEDURE actualizar_precios_tienda (
        p_store_id IN NUMBER,
        p_porcentaje_aumento IN NUMBER
    ) IS BEGIN
UPDATE products
SET unit_price = unit_price * (1 + (p_porcentaje_aumento / 100))
WHERE product_id IN (
        SELECT product_id
        FROM inventory
        WHERE store_id = p_store_id
    );
COMMIT;
DBMS_OUTPUT.PUT_LINE(
    'Precios actualizados para la tienda ' || p_store_id
);
END;
/
/*
 6. Crear un trigger que automáticamente registre cambios de inventario El trigger debe capturar los cambios en el campo product_inventory de
 la tabla INVENTORY e insertar los cambios en una tabla de historial de inventario.
 */
-- Creación de la tabla de historial
CREATE TABLE inventory_history (
    history_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    product_id NUMBER,
    store_id NUMBER,
    old_inventory NUMBER,
    new_inventory NUMBER,
    change_date DATE DEFAULT SYSDATE
);
-- Creación del Trigger
CREATE OR REPLACE TRIGGER trg_inventory_changes
AFTER
UPDATE OF product_inventory ON inventory FOR EACH ROW BEGIN IF :OLD.product_inventory != :NEW.product_inventory THEN
INSERT INTO inventory_history (
        product_id,
        store_id,
        old_inventory,
        new_inventory
    )
VALUES (
        :OLD.product_id,
        :OLD.store_id,
        :OLD.product_inventory,
        :NEW.product_inventory
    );
END IF;
END;
/
/*
 7. Crear una vista materializada que calcule el valor total de inventario por tienda 
 Con el objeto de mejorar el rendimiento en la generación de reportes de valor de inventario. Use las tablas INVENTORY y PRODUCTS. Establecer que la vista se actualice semanalmente.
 */
CREATE MATERIALIZED VIEW mv_inventory_value REFRESH COMPLETE START WITH SYSDATE NEXT SYSDATE + 7 AS
SELECT i.store_id,
    s.store_name,
    SUM(i.product_inventory * p.unit_price) AS total_value
FROM inventory i
    JOIN products p ON i.product_id = p.product_id
    JOIN stores s ON i.store_id = s.store_id
GROUP BY i.store_id,
    s.store_name;
/*
 8. Implementar una función almacenada que calcule el valor total de una orden
 La función debe recibir el order_id y devolver el valor total de la orden basado en los productos y cantidades en ORDER_ITEMS. 
 Ejecutar la función en conjunto con una consulta sobre ORDERS.
 */
CREATE OR REPLACE FUNCTION calcular_total_orden (p_order_id IN NUMBER) RETURN NUMBER IS v_total NUMBER := 0;
BEGIN
SELECT NVL(SUM(unit_price * quantity), 0) INTO v_total
FROM order_items
WHERE order_id = p_order_id;
RETURN v_total;
END;
/
/*
 9. Crear un cursor explícito que liste todos los productos de una tienda específica y calcule el valor total del inventario
 
 Se debe crear un procedimiento que use cursores para obtener todos los productos de una tienda y calcular el valor total del inventario en esa tienda.
 */
CREATE OR REPLACE PROCEDURE reporte_inventario_tienda (p_store_id NUMBER) IS CURSOR c_productos IS
SELECT p.product_name,
    i.product_inventory,
    p.unit_price,
    (i.product_inventory * p.unit_price) AS valor_producto
FROM inventory i
    JOIN products p ON i.product_id = p.product_id
WHERE i.store_id = p_store_id;
v_total_inventario NUMBER := 0;
BEGIN DBMS_OUTPUT.PUT_LINE('--- Inventario Tienda ' || p_store_id || ' ---');
FOR r_producto IN c_productos LOOP DBMS_OUTPUT.PUT_LINE(
    r_producto.product_name || ' | Cantidad: ' || r_producto.product_inventory
);
v_total_inventario := v_total_inventario + r_producto.valor_producto;
END LOOP;
DBMS_OUTPUT.PUT_LINE('VALOR TOTAL: $' || v_total_inventario);
END;
/
/*
 10. Crear un cursor explícito que recorra las órdenes pendientes y actualice su estado Aumentar el estado de aquellas órdenes que cumplen ciertos criterios
 (por ejemplo, órdenes con más de 5 días sin procesar).
 */
CREATE OR REPLACE PROCEDURE actualizar_ordenes_pendientes IS CURSOR c_ordenes IS
SELECT order_id,
    order_status
FROM orders
WHERE order_status = 'PENDING'
    AND order_tms < SYSDATE - 5 FOR
UPDATE;
BEGIN FOR r_orden IN c_ordenes LOOP
UPDATE orders
SET order_status = 'CANCELLED'
WHERE CURRENT OF c_ordenes;
END LOOP;
COMMIT;
END;
/
/*
 11. Crear un procedimiento almacenado que reciba el ID de una tienda y devuelva el número total de órdenes y el valor total de ventas 
 Usar parámetros IN/OUT en procedimientos almacenados. Crear el procedimiento con parámetros de entrada y salida. Ejecutar el procedimiento y verificar los valores devueltos.
 */
CREATE OR REPLACE PROCEDURE obtener_estadisticas_tienda (
        p_store_id IN NUMBER,
        p_total_ordenes OUT NUMBER,
        p_valor_ventas OUT NUMBER
    ) IS BEGIN
SELECT COUNT(DISTINCT o.order_id),
    NVL(SUM(oi.quantity * oi.unit_price), 0) INTO p_total_ordenes,
    p_valor_ventas
FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
WHERE o.store_id = p_store_id;
END;
/
/*
 12. Desarrollar un procedimiento almacenado que realice una inserción en la tabla CUSTOMERS
 Manejando los posibles errores (por ejemplo, intentar insertar un cliente con un email duplicado). Implementar manejo de excepciones para evitar la interrupción del proceso.
 */
CREATE OR REPLACE PROCEDURE insertar_cliente (
        p_email_address IN VARCHAR2,
        p_full_name IN VARCHAR2
    ) IS -- Se mapea el error ORA-00001 (Violación de restricción única)
    e_email_duplicado EXCEPTION;
PRAGMA EXCEPTION_INIT(e_email_duplicado, -1);
BEGIN
INSERT INTO customers (email_address, full_name)
VALUES (p_email_address, p_full_name);
COMMIT;
DBMS_OUTPUT.PUT_LINE('Cliente registrado exitosamente.');
EXCEPTION
WHEN e_email_duplicado THEN DBMS_OUTPUT.PUT_LINE(
    'Error: El correo electrónico ya está registrado.'
);
ROLLBACK;
WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('Error inesperado: ' || SQLERRM);
ROLLBACK;
END;
/
/*
 13. Crear un trigger que audite los cambios en el campo unit_price de la tabla PRODUCTS
 Registrar esos cambios en una tabla de auditoría. Para ello se debe crear una tabla de auditoría que capture los cambios de precio.
 */
CREATE TABLE price_audit (
    audit_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    product_id NUMBER,
    old_price NUMBER,
    new_price NUMBER,
    change_date DATE DEFAULT SYSDATE,
    changed_by VARCHAR2(100)
);
--Trigger
CREATE OR REPLACE TRIGGER trg_audit_price
AFTER
UPDATE OF unit_price ON products FOR EACH ROW BEGIN IF :OLD.unit_price != :NEW.unit_price THEN
INSERT INTO price_audit (product_id, old_price, new_price, changed_by)
VALUES (
        :OLD.product_id,
        :OLD.unit_price,
        :NEW.unit_price,
        USER
    );
END IF;
END;
/